using Microsoft.Extensions.Primitives;
using System.Net;

namespace FluentResultsSerialization;

internal sealed class SerializationData
{
    /// <summary>
    /// The Content-Type header of the HTTP response.
    /// </summary>
    public string ContentType { get; init; } = string.Empty;

    /// <summary>
    /// Additional headers of the HTTP response.
    /// </summary>
    public Dictionary<string, StringValues> Headers { get; init; } = new();

    /// <summary>
    /// A URI reference [<see href="https://datatracker.ietf.org/doc/html/rfc3986">RFC3986</see>] that identifies the
    /// problem type.This specification encourages that, when
    /// dereferenced, it provide human-readable documentation for the
    /// problem type (e.g., using HTML
    /// [<see href="https://datatracker.ietf.org/doc/html/rfc7807#ref-W3C.REC-html5-20141028">W3C.REC-html5-20141028</see>]).
    /// When this member is not present, its value is assumed to be
    /// "about:blank".
    /// </summary>
    public string? Type { get; init; }

    /// <summary>
    /// A short, human-readable summary of the problem
    /// type.It SHOULD NOT change from occurrence to occurrence of the
    /// problem, except for purposes of localization(e.g., using
    /// proactive content negotiation; see
    /// <see href="https://datatracker.ietf.org/doc/html/rfc7231#section-3.4">[RFC7231], Section 3.4</see>.
    /// </summary>
    public string? Title { get; init; }

    /// <summary>
    /// The HTTP status code
    /// (<see href="https://datatracker.ietf.org/doc/html/rfc7231#section-6">[RFC7231], Section 6</see>)
    /// generated by the origin server for this occurrence of the problem.
    /// </summary>
    public HttpStatusCode Status { get; init; }

    /// <summary>
    /// A human-readable explanation specific to this
    /// occurrence of the problem.
    /// </summary>
    public string? Detail { get; init; }

    /// <summary>
    /// A URI reference that identifies the specific
    /// occurrence of the problem.It may or may not yield further
    /// information if dereferenced.
    /// </summary>
    public string? Instance { get; init; }

    /// <summary>
    /// Conveys additional, problem-specific information.
    /// </summary>
    public Dictionary<string, object?> Extensions { get; init; } = new();
}
